### ISSUE TITLE
Client-side Exception: TypeError: Cannot Read Properties of Undefined (reading 'data')

### ISSUE THREAD

**Issue by errhythm** [jonogon/jonogon-mono#73]
Encountering a client-side exception on the application, which results in the following error message being displayed:
![image](https://github.com/user-attachments/assets/62a6533d-9c9b-4748-afcc-d585bf9e07dd)

```
TypeError: Cannot read properties of undefined (reading 'data')
    at https://jonogon.org/_next/static/chunks/app/page-d8c820dff5405d88.js:1:5792
    at Array.map (<anonymous>)
    at _ (https://jonogon.org/_next/static/chunks/app/page-d8c820dff5405d88.js:1:5703)
    at rE (https://jonogon.org/_next/static/chunks/abf17911-43004f859fc518c6.js:1:40341)
    at l$ (https://jonogon.org/_next/static/chunks/abf17911-43004f859fc518c6.js:1:59316)
    at iZ (https://jonogon.org/_next/static/chunks/abf17911-43004f859fc518c6.js:1:117923)
    at ia (https://jonogon.org/_next/static/chunks/abf17911-43004f859fc518c6.js:1:95162)
    at https://jonogon.org/_next/static/chunks/abf17911-43004f859fc518c6.js:1:94984
    at il (https://jonogon.org/_next/static/chunks/abf17911-43004f859fc518c6.js:1:94991)
    at oJ (https://jonogon.org/_next/static/chunks/abf17911-43004f859fc518c6.js:1:92347)

```

Steps:
1. Go to https://jonogon.org/?type=own

**Comment by errhythm** [comment]
The issue has been fixed with the latest update.
